# Generated by Django 5.2.17 on 2026-09-06 19:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('energy', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('food', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('phone', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('cut', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(50)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('user', 'month'), name='unique_user_month'), models.CheckConstraint(condition=models.Q(('month__day', 1)), name='month_first_day'), models.CheckConstraint(condition=models.Q(('cut__gte', 0), ('cut__lte', 50)), name='valid_cut'), models.CheckConstraint(condition=models.Q(('income__gte', 0), ('income__lte', 1000000)), name='valid_income'), models.CheckConstraint(condition=models.Q(('rent__gte', 0), ('rent__lte', 1000000)), name='valid_rent'), models.CheckConstraint(condition=models.Q(('energy__gte', 0), ('energy__lte', 1000000)), name='valid_energy'), models.CheckConstraint(condition=models.Q(('food__gte', 0), ('food__lte', 1000000)), name='valid_food'), models.CheckConstraint(condition=models.Q(('transport__gte', 0), ('transport__lte', 1000000)), name='valid_transport'), models.CheckConstraint(condition=models.Q(('phone__gte', 0), ('phone__lte', 1000000)), name='valid_phone'), models.CheckConstraint(condition=models.Q(('insurance__gte', 0), ('insurance__lte', 1000000)), name='valid_insurance'), models.CheckConstraint(condition=models.Q(('other__gte', 0), ('other__lte', 1000000)), name='valid_other')],
            },
        ),
    ]
